baseURL = "/"
languageCode = "en-us"
title = "Aha001 Team Site"
copyright = "The Aha001 Team"
theme = 'cactus'

[params]

colortheme = "white"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Team Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3